### ISSUE TITLE
is it possible to train the new superpoint and superglue?

### ISSUE THREAD

**Issue by atomishcv** [gouthamvgk/SuperGlue_training#12]
Hi, thank you for your great work! i want to train a new CNN feature map in superpoint, the loss function is useful for training the superpoint and superglue?

**Comment by gouthamvgk** [comment]
This repo can only train the superglue network. Superpoint is used with fixed weights and not trainable

**Comment by atomishcv** [comment]
thank you for your reply! can i modify the code to train the superpoint and the superglue?
