### ISSUE TITLE
Error while training the SuperGlue

### ISSUE THREAD

**Issue by Shuhul24** [gouthamvgk/SuperGlue_training#18]
Hi.
I have been following the code that has been shared in the respective github repository. But on executing the code I am ending with an error as follow:
```python
Traceback (most recent call last):
  File "/home/shuhulh/SuperGlue_training/train_superglue.py", line 252, in <module>
    train(config, opt.local_rank)
  File "/home/shuhulh/SuperGlue_training/train_superglue.py", line 139, in train
    superpoint_results = superpoint_model.forward_train({'homography': homographies, 'image': orig_warped})
  File "/home/shuhulh/SuperGlue_training/models/superpoint.py", line 260, in forward_train
    results.append(remove_borders_projected(k, s, self.config['remove_borders'], h*8, w*8, homo_matrix))
  File "/home/shuhulh/SuperGlue_training/models/superpoint.py", line 73, in remove_borders_projected
    projected_keypoints = warp_keypoints(keypoints, torch.inverse(homo_matrix))
  File "/home/shuhulh/SuperGlue_training/models/superpoint.py", line 103, in warp_keypoints
    dest /= dest[:, 2:3]
RuntimeError: unsupported operation: some elements of the input tensor and the written-to tensor refer to a single memory location. Please clone() the tensor before performing the operation.
```

How to overcome this error?

**Comment by gouthamvgk** [comment]
Did you make any changes in the code that could have led to this?. The mainline code used to run without any issues with the pytorch version given in README. I just tested that function alone and it works fine. If not sure what changed could have caused this, I would suggest to use the clone() operation as mentioned in the error message

**Comment by Shuhul24** [comment]
The only change that I made was regarding the path to the coco dataset in `configs/coco_config.yaml` where the consists three folders, `train2017`, `validation2017` and `annotations`. Also the version of pytorch is `1.13.1`.

I am trying to understand the error but I don't follow much of how to debug this error. Can you help me figure it out?

**Comment by 1061700625** [comment]
superpoint.py文件，把
```
dest /= dest[:, 2:3]
```
改成
```
# 使用非就地操作进行更新
dest = dest / dest[:, 2:3]  
```
