### ISSUE TITLE
How to train superglue in my own datasets?

### ISSUE THREAD

**Issue by zhanghua7099** [gouthamvgk/SuperGlue_training#2]
This code seems to only support COCO 2017 dataset. How to train in another dataset? Can you give some advice?

**Comment by gouthamvgk** [comment]
Currently, the dataloader is coded in such a way that it accepts coco format only. You can easily convert your dataset into coco format. COCO format is as follow,
DATASET_FOLDER:
   annotations/
       instances_train2017.json -> Contains training images info
       instances_val2017.json -> Contains validation images info
  train2017/
       contains the training images
  val2017/
       contains the validation images

You can refer to the sample dataset at https://drive.google.com/drive/folders/1LrS2TKsgd1OVvrfObirDQBCaE4u2NSUN?usp=sharing if you want.(Sample dataset contains only train json and train images, have to create val json and images similarly)

**Comment by zhanghua7099** [comment]
Thank you for your reply!

**Comment by zhangsngood** [comment]
> Thank you for your reply!



> This code seems to only support COCO 2017 dataset. How to train in another dataset? Can you give some advice?

Have you realized it？Now I want to use my own datasets to train the SuperGlue, but the error happens when training. So I want to ask if you have achieved it, and I want some suggestions from you.

**Comment by Shafaq-S** [comment]
> > Thank you for your reply!
> 
> > This code seems to only support COCO 2017 dataset. How to train in another dataset? Can you give some advice?
> 
> Have you realized it？Now I want to use my own datasets to train the SuperGlue, but the error happens when training. So I want to ask if you have achieved it, and I want some suggestions from you.

Did any of you manage to train it on your own dataset? I have a similar problem where I'll be annotating my own data but unsure about the annotations format. Please refer to issue # 17.

**Comment by Shuhul24** [comment]
@Shafaq-S Hey, did you get the solution on how to manage to generate such files for our respective custom dataset?

**Comment by Shafaq-S** [comment]
> @Shafaq-S Hey, did you get the solution on how to manage to generate such files for our respective custom dataset?

I decided to not go with COCO format and defined my custom json annotations. Currently, I'm in the process of annotating my data. Still have to test the code with it.

**Comment by Shuhul24** [comment]
@Shafaq-S Hey any updates regarding the json format of annotations? Need some help regarding the same.
