### ISSUE TITLE
Comparison between LayerNorm and BatchNorm

### ISSUE THREAD

**Issue by hit2sjtu** [gouthamvgk/SuperGlue_training#6]
Hi, nice work here
I found in your code one can choose between LayerNorm and BatchNorm. Did you find any performance difference here?

https://github.com/gouthamvgk/SuperGlue_training/blob/2a13bba792b1738819a30cd28551431d6e4ef493/models/superglue.py#L71

Thanks

**Comment by gouthamvgk** [comment]
Just had the option. Didn't try it out
